CREATE TABLE authority (
	user_id VARCHAR(50) PRIMARY KEY,
	user_authority VARCHAR(20) NOT NULL DEFAULT 'ROLE_USER',
	FOREIGN KEY (user_id) REFERENCES users(user_id) ON UPDATE CASCADE ON DELETE CASCADE
);